# Site settings
title: Crowd Control Ninja, LLC
email: info@crowdcontrol.ninja
description: "A products and services firm dedicated to support of crowd-sourced campaigns."
baseurl: ""
url: "http://crowdcontrolninja.github.io"
twitter_username: crowdcontrolninja
github_username:  crowdcontrolninja

# Build settings
markdown: kramdown
permalink: pretty
